FROM node:16.6.1 as build

WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn build:staging
#RUN npm install -g serve


FROM nginx
COPY ./nginx-stg.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
