#!/bin/sh

echo ECR_REGISTRY=$ECR_REGISTRY >> .env
echo CI_PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE >> .env
echo CI_PROJECT_NAME=$CI_PROJECT_NAME >> .env
echo IMAGE=${ECR_REGISTRY}/${CI_PROJECT_NAMESPACE} >> .env
echo STAGING_CEX_FRONT_IMAGE=${IMAGE}:${CI_PROJECT_NAME} >> .env
